/* eslint-env jest */
import * as swr from "../index.js";
import fs from "node:fs";
import { currentRoundHasUnsubmittedMatches } from "../tournament/rounds.js";

const loopWhileNotNull = (original, callback) => {
  let value = original;
  let copy = original;
  while (value != null) {
    copy = value;
    value = callback(value);
  }
  return copy;
};

const identity = (x) => x;

const threadFunctions = (value, ...functions) =>
  functions.reduce((res, f) => f(res), value);

const calculateScoreWithPriorities = (players, priorities, p1, p2) => {
  const player1 = players.find((it) => it.id === p1);
  const player2 = players.find((it) => it.id === p2);

  const priority1 = priorities.indexOf(player1.data);
  const priority2 = priorities.indexOf(player2.data);

  if (priority1 === priority2) {
    return [1, 1];
  }
  if (priority2 > priority1) {
    return [0, 3];
  }
  return [3, 0];
};

const runTournamentWithPriorities = (participants, priorities) => {
  const initialT = swr.createTournament(participants);
  return loopWhileNotNull(initialT, (tournament) => {
    if (swr.isTournamentComplete(tournament)) {
      return null;
    }
    if (!currentRoundHasUnsubmittedMatches(tournament.rounds)) {
      return swr.computeNextRound(tournament);
    }
    const { rounds, players } = tournament;
    const currentRoundIndex = rounds.length - 1;
    const currentRound = rounds[currentRoundIndex];

    const functions = currentRound.map((match, matchIndex) => {
      const { p1, p2, score } = match;
      if (score.length > 0) return identity;
      const [scoreP1, scoreP2] = calculateScoreWithPriorities(
        players,
        priorities,
        p1,
        p2,
      );
      return (t) => swr.submitScores(t, matchIndex, scoreP1, scoreP2);
    });

    return threadFunctions(tournament, ...functions);
  });
};

test("should run tournament with 8 participants", () => {
  const participants = [
    "Victoria",
    "Patricio",
    "Valentino",
    "Catalina",
    "Raul",
    "Carla",
    "Fátima",
    "Emiliano",
  ];

  const priorities = ["Catalina", "Patricio"];
  const finalTournament = runTournamentWithPriorities(participants, priorities);

  const placings = swr.computePlacings(finalTournament);
  const [top1, top2] = placings;
  expect(top1).toEqual(
    expect.objectContaining({
      data: "Patricio",
      points: 9,
    }),
  );
  expect(top2).toEqual(
    expect.objectContaining({
      data: "Catalina",
      points: 6,
    }),
  );
});

test("should run tournament with 15 participants", () => {
  const participants = [
    "Victoria",
    "Patricio",
    "Valentino",
    "Catalina",
    "Raul",
    "Carla",
    "Fátima",
    "Emiliano",
    "Alvaro",
    "Lorenzo",
    "Edmundo",
    "Leopoldo",
    "Ramon",
    "Leo",
    "Ramiro",
  ];

  const priorities = ["Fátima", "Raul", "Victoria"];
  const finalTournament = runTournamentWithPriorities(participants, priorities);

  const placings = swr.computePlacings(finalTournament);
  const [top1, top2, top3] = placings;
  expect(top1).toEqual(
    expect.objectContaining({
      data: "Victoria",
      points: 12,
    }),
  );
  expect(top2).toEqual(
    expect.objectContaining({
      data: "Raul",
      points: 9,
    }),
  );
  expect(top3).toEqual(
    expect.objectContaining({
      data: "Fátima",
      points: 6,
    }),
  );

  // last place should be a bye player
  const lastPlace = placings[placings.length - 1];
  expect(lastPlace).toEqual(expect.objectContaining({ data: null, points: 0 }));
});

test("should run tournament with 16 participants", () => {
  const participants = [
    "Victoria",
    "Patricio",
    "Valentino",
    "Catalina",
    "Raul",
    "Carla",
    "Fátima",
    "Emiliano",
    "Alvaro",
    "Lorenzo",
    "Edmundo",
    "Leopoldo",
    "Ramon",
    "Leo",
    "Ramiro",
    "Jorge",
  ];

  const priorities = ["Jorge", "Carla", "Leo"];
  const finalTournament = runTournamentWithPriorities(participants, priorities);

  const placings = swr.computePlacings(finalTournament);
  const [top1, top2, top3] = placings;
  expect(top1).toEqual(
    expect.objectContaining({
      data: "Leo",
      points: 12,
    }),
  );
  expect(top2).toEqual(
    expect.objectContaining({
      data: "Carla",
      points: 9,
    }),
  );
  expect(top3).toEqual(
    expect.objectContaining({
      data: "Jorge",
      points: 6,
    }),
  );
});

test("should run tournament with 24 participants", () => {
  const participants = [
    "Victoria",
    "Patricio",
    "Valentino",
    "Catalina",
    "Raul",
    "Carla",
    "Fátima",
    "Emiliano",
    "Alvaro",
    "Lorenzo",
    "Edmundo",
    "Leopoldo",
    "Ramon",
    "Leo",
    "Ramiro",
    "Jorge",
    "Angelica",
    "Mario",
    "Belinda",
    "Florencia",
    "Vanessa",
    "Marcos",
    "Edgar",
    "Javier",
  ];

  const priorities = ["Ramon", "Marcos", "Carla"];
  const finalTournament = runTournamentWithPriorities(participants, priorities);

  const placings = swr.computePlacings(finalTournament);
  const [top1, top2, top3] = placings;
  expect(top1).toEqual(
    expect.objectContaining({
      data: "Carla",
      points: 15,
    }),
  );
  expect(top2).toEqual(
    expect.objectContaining({
      data: "Marcos",
      points: 12,
    }),
  );
  expect(top3).toEqual(
    expect.objectContaining({
      data: "Ramon",
      points: 9,
    }),
  );
});

test("should run tournament with 29 participants", () => {
  const participants = [
    "Victoria",
    "Patricio",
    "Valentino",
    "Catalina",
    "Raul",
    "Carla",
    "Fátima",
    "Emiliano",
    "Alvaro",
    "Lorenzo",
    "Edmundo",
    "Leopoldo",
    "Ramon",
    "Leo",
    "Ramiro",
    "Jorge",
    "Angelica",
    "Mario",
    "Belinda",
    "Florencia",
    "Vanessa",
    "Marcos",
    "Edgar",
    "Javier",
    "Mauro",
    "Bryan",
    "Kevin",
    "Flor",
    "Luis",
  ];

  const priorities = ["Ramiro", "Kevin", "Bryan"];
  const finalTournament = runTournamentWithPriorities(participants, priorities);

  const placings = swr.computePlacings(finalTournament);
  const [top1, top2, top3] = placings;
  expect(top1).toEqual(
    expect.objectContaining({
      data: "Bryan",
      points: 15,
    }),
  );
  expect(top2).toEqual(
    expect.objectContaining({
      data: "Kevin",
      points: 12,
    }),
  );
  expect(top3).toEqual(
    expect.objectContaining({
      data: "Ramiro",
      points: 9,
    }),
  );

  // last place should be a bye player
  const lastPlace = placings[placings.length - 1];
  expect(lastPlace).toEqual(expect.objectContaining({ data: null, points: 0 }));
});

test("should run tournament with 32 participants", () => {
  const participants = [
    "Victoria",
    "Patricio",
    "Valentino",
    "Catalina",
    "Raul",
    "Carla",
    "Fátima",
    "Emiliano",
    "Alvaro",
    "Lorenzo",
    "Edmundo",
    "Leopoldo",
    "Ramon",
    "Leo",
    "Ramiro",
    "Jorge",
    "Angelica",
    "Mario",
    "Belinda",
    "Florencia",
    "Vanessa",
    "Marcos",
    "Edgar",
    "Javier",
    "Mauro",
    "Bryan",
    "Kevin",
    "Flor",
    "Luis",
    "Diego",
    "Pedro",
    "Moises",
  ];

  const priorities = ["Belinda", "Alvaro", "Florencia"];
  const finalTournament = runTournamentWithPriorities(participants, priorities);

  const placings = swr.computePlacings(finalTournament);
  const [top1, top2, top3] = placings;
  expect(top1).toEqual(
    expect.objectContaining({
      data: "Florencia",
      points: 15,
    }),
  );
  expect(top2).toEqual(
    expect.objectContaining({
      data: "Alvaro",
      points: 12,
    }),
  );
  expect(top3).toEqual(
    expect.objectContaining({
      data: "Belinda",
      points: 9,
    }),
  );
});
test("should run tournament with 311 participants", () => {
  const participants = [
    "Erda,Terrington",
    "Kaleena,Laimable",
    "Kelwin,Caulcutt",
    "Noell,Stuckes",
    "Angel,Giorgetti",
    "Abbi,Mion",
    "Shanan,Cheesley",
    "Jaclyn,Coverley",
    "Dev,Padilla",
    "Crawford,Peckham",
    "Annaliese,Waiton",
    "Merci,Rallin",
    "Kincaid,Cockney",
    "Aridatha,Cronk",
    "Douglass,Jersch",
    "Hasheem,Gert",
    "Aurie,Maffini",
    "Mill,Grovier",
    "Lethia,Dudin",
    "Iormina,Pargiter",
    "Faydra,Pretti",
    "Nevin,Haddleton",
    "Peyton,Vella",
    "Marquita,Paradis",
    "Alick,Eaton",
    "Doris,Faircley",
    "Lauren,Bockmann",
    "Nissa,Liveing",
    "Titus,Jenner",
    "Elna,Ruslen",
    "Dalli,Glasson",
    "Aubree,Graffham",
    "Franklin,Veysey",
    "Jennilee,Howroyd",
    "Willie,Chittleburgh",
    "Madelina,Haseldine",
    "Darleen,O'Rourke",
    "Dion,Roubert",
    "Felipe,O'Kynsillaghe",
    "Micah,Claris",
    "Beulah,Delacoste",
    "Tarah,Slot",
    "Gay,Challes",
    "Carol-jean,Perotti",
    "Aubine,Bysaker",
    "Misha,Beteriss",
    "Pierette,Gillcrist",
    "Saundra,Droogan",
    "Calida,Hardisty",
    "Roby,Schuricht",
    "Ange,Senten",
    "Nixie,Gomery",
    "Melisenda,Elnor",
    "Marshal,Fowlie",
    "Sayre,Geffcock",
    "Rawley,Cassidy",
    "Brigham,Coad",
    "Katrina,Saipy",
    "Carey,Upshall",
    "Jeanette,Thomas",
    "Hilary,de Keep",
    "Joli,Oseman",
    "Ignatius,Macro",
    "Martie,Wilmut",
    "Janine,Dudgeon",
    "Kenon,Copozio",
    "Jecho,Winley",
    "Haydon,Dreakin",
    "Thorny,Carnock",
    "Ardelia,Itzkovitch",
    "Saree,Rolfe",
    "Brade,Romanini",
    "Zebulon,Penas",
    "Sibel,Bloss",
    "Skip,Mechi",
    "Ealasaid,Bodicum",
    "Elnora,Nye",
    "Christiane,Hamman",
    "Kenna,Huff",
    "Nathan,Lusk",
    "Hollyanne,Spottiswood",
    "Mark,Millam",
    "Henrik,Cawson",
    "Starlene,Hassur",
    "Omar,Chadney",
    "Melessa,Pentycross",
    "Tammi,Bescoby",
    "Warren,Durden",
    "Germayne,Blanking",
    "Valene,Sweett",
    "Pavel,Dell Casa",
    "Hashim,Barbosa",
    "Adolpho,Jelliman",
    "Whitman,Breacher",
    "Yardley,Habden",
    "Wilton,Hackly",
    "Lon,Bevan",
    "Brander,Lathom",
    "Jaynell,Skillings",
    "Nariko,MacAloren",
    "Sabra,Grocock",
    "Donni,Flatt",
    "Winifield,Feasby",
    "Evvy,Howard - Gater",
    "Evonne,Grenshields",
    "Addison,Child",
    "Huberto,McLeoid",
    "Ricky,Illing",
    "Berke,Bohin",
    "Pietrek,Rimer",
    "Maure,Barney",
    "Sascha,Puddin",
    "Daveen,Geist",
    "Putnem,Kemitt",
    "Adaline,Dedney",
    "Harry,Smurfitt",
    "Robena,Barton",
    "Jessey,Piner",
    "Stacee,Jasik",
    "Tally,Roan",
    "Emmet,Girton",
    "Glynis,Ricketts",
    "Jody,Obey",
    "Sergent,Southey",
    "Sandie,Mc Carrick",
    "Brody,Sawdy",
    "Lynelle,Brown",
    "Griffith,Terrington",
    "Billy,Lurriman",
    "Caroljean,Nickell",
    "Cornelle,Eccott",
    "Salli,Brayson",
    "Scottie,Farguhar",
    "Jackie,Seligson",
    "Gavin,Sadgrove",
    "Stanley,Schapero",
    "Correy,Hagstone",
    "Lacey,Hogben",
    "Amerigo,Carvil",
    "Welsh,Pestridge",
    "Ulrikaumeko,Macconaghy",
    "Penn,Housley",
    "Clim,Cutting",
    "Leshia,Sherington",
    "Alison,Quimby",
    "Emeline,Hebbron",
    "Jillian,Jenckes",
    "Lorrie,Mucklestone",
    "Malachi,Von Salzberg",
    "Hallsy,Sewley",
    "Cole,Bullerwell",
    "Missie,Elles",
    "Nerte,Hundal",
    "Hali,Cressey",
    "Devinne,Whereat",
    "Jayson,Stiggers",
    "Brinna,Shorthill",
    "Costa,Hallgalley",
    "Mendy,Korneichuk",
    "Dexter,Tollerton",
    "Jimmy,Krammer",
    "Juieta,Dosdale",
    "Trixi,Issac",
    "Bobine,Phillipps",
    "Federica,Brunnen",
    "Karrah,Hawson",
    "Verna,Spear",
    "Gracie,Tomashov",
    "Waylin,Palliser",
    "Rodina,Threadgould",
    "Lyle,Bisiker",
    "Margaretta,Haestier",
    "Cathrin,Barents",
    "Cori,Shorton",
    "Pascal,Peperell",
    "Kayle,Applegate",
    "Mord,Rosbrough",
    "Jamaal,Prince",
    "Gerrie,Birkhead",
    "Caddric,Baudain",
    "Latashia,Cartmer",
    "Harbert,Renhard",
    "Artemus,Atack",
    "Miquela,Euler",
    "Edita,Radnage",
    "Tiffie,Portigall",
    "Cornelius,Hoyland",
    "Eustace,Toombs",
    "Cointon,Bills",
    "Veda,Harget",
    "Jacquenette,Clapton",
    "Heddie,Ryburn",
    "Borden,Guesford",
    "Cammy,Oxborough",
    "Jodi,Klimkov",
    "Cecil,Ferrillo",
    "Tine,Higgen",
    "Nichols,Hatchette",
    "Bettina,Hadlee",
    "Koralle,Dennes",
    "Timmy,Edgeon",
    "Jake,Shieber",
    "Paloma,Whitford",
    "Mallorie,Cleminshaw",
    "Meredithe,Swan",
    "Micki,Skiplorne",
    "Wilfred,Imrie",
    "Shelbi,Lethbrig",
    "Vally,Yosevitz",
    "Britte,Gritland",
    "Fanechka,Brognot",
    "Gwenneth,Norval",
    "Alene,Sweeting",
    "Johanna,Dalziell",
    "Ruy,Lusted",
    "Web,Blinde",
    "Cinda,Edser",
    "Lesya,Woodfield",
    "Nikolai,Shevelin",
    "Billi,Priestland",
    "Veradis,Peggrem",
    "Penn,Sor",
    "Danna,Baudasso",
    "Mikael,Feaks",
    "Joli,Valentine",
    "Benedikta,Sidery",
    "Darrel,Killcross",
    "Lorie,Gingle",
    "Mignonne,Ghione",
    "Kiele,Fauguel",
    "Wilone,Woofenden",
    "Simon,Renfield",
    "Roberta,Swiffin",
    "Mirilla,Rough",
    "Dyane,Vanderplas",
    "Nedda,Stollmeyer",
    "Schuyler,Jon",
    "Gilberte,Lenahan",
    "Bevan,Caldera",
    "Sheeree,Chessum",
    "Borg,Crennan",
    "Xaviera,Donati",
    "Sula,Patey",
    "Westbrook,Geoghegan",
    "Pearl,Fritchley",
    "Eward,Frankowski",
    "Moreen,Messruther",
    "Cchaddie,Jorg",
    "Rafe,Marson",
    "Tarrah,Kadar",
    "Rhoda,McCoughan",
    "Valentine,Zarb",
    "Tomasine,Borsi",
    "Rafaelita,Storton",
    "Waldemar,Lockey",
    "Aurelia,Paine",
    "Nathaniel,Godney",
    "Vonnie,Wardhaw",
    "Alfonse,Pitney",
    "Ramonda,Bleesing",
    "Bartel,Montier",
    "Claus,Franzke",
    "Pennie,Ivanchin",
    "Mady,Iapico",
    "Bambi,Kobera",
    "Layton,Shurman",
    "Ali,Ferraraccio",
    "Onfroi,De Dantesie",
    "Hermine,Ibanez",
    "Kerby,Grigorushkin",
    "Rowland,Mabone",
    "Arabelle,Ganny",
    "Clint,Freeman",
    "Emelyne,Flaherty",
    "Nikolia,Bramhall",
    "Edythe,Roskell",
    "Moss,Lourens",
    "Casey,Venners",
    "Theodosia,Weymouth",
    "Cass,Gunson",
    "Tobey,Anselmi",
    "Hillard,Carless",
    "Cody,Piccop",
    "Amerigo,Kopecka",
    "Stuart,Knatt",
    "Giacomo,Ivanenko",
    "Penelopa,Lethebridge",
    "Franzen,Petit",
    "Genevra,Nijssen",
    "Shelli,Eliyahu",
    "Theda,Dowell",
    "Sandy,Gutridge",
    "Nickolaus,Gehrtz",
    "Tamera,Harrington",
    "Gray,Baudesson",
    "Shayne,Lamball",
    "Inglis,Wiltsher",
    "Timothy,McShirrie",
    "Harp,Huntall",
    "Maryanna,Druhan",
    "Jamey,Dissman",
    "Addi,Tidball",
    "Denver,Rings",
    "Tim,Grigoriev",
    "Saul,Alben",
    "Glyn,Kernley",
    "Abby,Pinkard",
    "Brendis,Hedlestone",
    "Leanna,Raithbie",
    "Eldin,Briggs",
    "Blondelle,Bigmore",
  ];

  const priorities = ["Bambi,Kobera", "Abby,Pinkard", "Dev,Padilla"];
  const finalTournament = runTournamentWithPriorities(participants, priorities);

  const placings = swr.computePlacings(finalTournament);
  const [top1, top2, top3] = placings;
  expect(top1).toEqual(
    expect.objectContaining({
      data: "Dev,Padilla",
      points: 27,
    }),
  );
  expect(top2).toEqual(
    expect.objectContaining({
      data: "Abby,Pinkard",
      points: 24,
    }),
  );
  expect(top3).toEqual(
    expect.objectContaining({
      data: "Bambi,Kobera",
      points: 21,
    }),
  );

  // last place should be a bye player
  const lastPlace = placings[placings.length - 1];
  expect(lastPlace).toEqual(expect.objectContaining({ data: null, points: 0 }));
});

test("should run tournament with 512 participants", () => {
  const participants = [
    "Erda,Terrington",
    "Kaleena,Laimable",
    "Kelwin,Caulcutt",
    "Noell,Stuckes",
    "Angel,Giorgetti",
    "Abbi,Mion",
    "Shanan,Cheesley",
    "Jaclyn,Coverley",
    "Dev,Padilla",
    "Crawford,Peckham",
    "Annaliese,Waiton",
    "Merci,Rallin",
    "Kincaid,Cockney",
    "Aridatha,Cronk",
    "Douglass,Jersch",
    "Hasheem,Gert",
    "Aurie,Maffini",
    "Mill,Grovier",
    "Lethia,Dudin",
    "Iormina,Pargiter",
    "Faydra,Pretti",
    "Nevin,Haddleton",
    "Peyton,Vella",
    "Marquita,Paradis",
    "Alick,Eaton",
    "Doris,Faircley",
    "Lauren,Bockmann",
    "Nissa,Liveing",
    "Titus,Jenner",
    "Elna,Ruslen",
    "Dalli,Glasson",
    "Aubree,Graffham",
    "Franklin,Veysey",
    "Jennilee,Howroyd",
    "Willie,Chittleburgh",
    "Madelina,Haseldine",
    "Darleen,O'Rourke",
    "Dion,Roubert",
    "Felipe,O'Kynsillaghe",
    "Micah,Claris",
    "Beulah,Delacoste",
    "Tarah,Slot",
    "Gay,Challes",
    "Carol-jean,Perotti",
    "Aubine,Bysaker",
    "Misha,Beteriss",
    "Pierette,Gillcrist",
    "Saundra,Droogan",
    "Calida,Hardisty",
    "Roby,Schuricht",
    "Ange,Senten",
    "Nixie,Gomery",
    "Melisenda,Elnor",
    "Marshal,Fowlie",
    "Sayre,Geffcock",
    "Rawley,Cassidy",
    "Brigham,Coad",
    "Katrina,Saipy",
    "Carey,Upshall",
    "Jeanette,Thomas",
    "Hilary,de Keep",
    "Joli,Oseman",
    "Ignatius,Macro",
    "Martie,Wilmut",
    "Janine,Dudgeon",
    "Kenon,Copozio",
    "Jecho,Winley",
    "Haydon,Dreakin",
    "Thorny,Carnock",
    "Ardelia,Itzkovitch",
    "Saree,Rolfe",
    "Brade,Romanini",
    "Zebulon,Penas",
    "Sibel,Bloss",
    "Skip,Mechi",
    "Ealasaid,Bodicum",
    "Elnora,Nye",
    "Christiane,Hamman",
    "Kenna,Huff",
    "Nathan,Lusk",
    "Hollyanne,Spottiswood",
    "Mark,Millam",
    "Henrik,Cawson",
    "Starlene,Hassur",
    "Omar,Chadney",
    "Melessa,Pentycross",
    "Tammi,Bescoby",
    "Warren,Durden",
    "Germayne,Blanking",
    "Valene,Sweett",
    "Pavel,Dell Casa",
    "Hashim,Barbosa",
    "Adolpho,Jelliman",
    "Whitman,Breacher",
    "Yardley,Habden",
    "Wilton,Hackly",
    "Lon,Bevan",
    "Brander,Lathom",
    "Jaynell,Skillings",
    "Nariko,MacAloren",
    "Sabra,Grocock",
    "Donni,Flatt",
    "Winifield,Feasby",
    "Evvy,Howard - Gater",
    "Evonne,Grenshields",
    "Addison,Child",
    "Huberto,McLeoid",
    "Ricky,Illing",
    "Berke,Bohin",
    "Pietrek,Rimer",
    "Maure,Barney",
    "Sascha,Puddin",
    "Daveen,Geist",
    "Putnem,Kemitt",
    "Adaline,Dedney",
    "Harry,Smurfitt",
    "Robena,Barton",
    "Jessey,Piner",
    "Stacee,Jasik",
    "Tally,Roan",
    "Emmet,Girton",
    "Glynis,Ricketts",
    "Jody,Obey",
    "Sergent,Southey",
    "Sandie,Mc Carrick",
    "Brody,Sawdy",
    "Lynelle,Brown",
    "Griffith,Terrington",
    "Billy,Lurriman",
    "Caroljean,Nickell",
    "Cornelle,Eccott",
    "Salli,Brayson",
    "Scottie,Farguhar",
    "Jackie,Seligson",
    "Gavin,Sadgrove",
    "Stanley,Schapero",
    "Correy,Hagstone",
    "Lacey,Hogben",
    "Amerigo,Carvil",
    "Welsh,Pestridge",
    "Ulrikaumeko,Macconaghy",
    "Penn,Housley",
    "Clim,Cutting",
    "Leshia,Sherington",
    "Alison,Quimby",
    "Emeline,Hebbron",
    "Jillian,Jenckes",
    "Lorrie,Mucklestone",
    "Malachi,Von Salzberg",
    "Hallsy,Sewley",
    "Cole,Bullerwell",
    "Missie,Elles",
    "Nerte,Hundal",
    "Hali,Cressey",
    "Devinne,Whereat",
    "Jayson,Stiggers",
    "Brinna,Shorthill",
    "Costa,Hallgalley",
    "Mendy,Korneichuk",
    "Dexter,Tollerton",
    "Jimmy,Krammer",
    "Juieta,Dosdale",
    "Trixi,Issac",
    "Bobine,Phillipps",
    "Federica,Brunnen",
    "Karrah,Hawson",
    "Verna,Spear",
    "Gracie,Tomashov",
    "Waylin,Palliser",
    "Rodina,Threadgould",
    "Lyle,Bisiker",
    "Margaretta,Haestier",
    "Cathrin,Barents",
    "Cori,Shorton",
    "Pascal,Peperell",
    "Kayle,Applegate",
    "Mord,Rosbrough",
    "Jamaal,Prince",
    "Gerrie,Birkhead",
    "Caddric,Baudain",
    "Latashia,Cartmer",
    "Harbert,Renhard",
    "Artemus,Atack",
    "Miquela,Euler",
    "Edita,Radnage",
    "Tiffie,Portigall",
    "Cornelius,Hoyland",
    "Eustace,Toombs",
    "Cointon,Bills",
    "Veda,Harget",
    "Jacquenette,Clapton",
    "Heddie,Ryburn",
    "Borden,Guesford",
    "Cammy,Oxborough",
    "Jodi,Klimkov",
    "Cecil,Ferrillo",
    "Tine,Higgen",
    "Nichols,Hatchette",
    "Bettina,Hadlee",
    "Koralle,Dennes",
    "Timmy,Edgeon",
    "Jake,Shieber",
    "Paloma,Whitford",
    "Mallorie,Cleminshaw",
    "Meredithe,Swan",
    "Micki,Skiplorne",
    "Wilfred,Imrie",
    "Shelbi,Lethbrig",
    "Vally,Yosevitz",
    "Britte,Gritland",
    "Fanechka,Brognot",
    "Gwenneth,Norval",
    "Alene,Sweeting",
    "Johanna,Dalziell",
    "Ruy,Lusted",
    "Web,Blinde",
    "Cinda,Edser",
    "Lesya,Woodfield",
    "Nikolai,Shevelin",
    "Billi,Priestland",
    "Veradis,Peggrem",
    "Penn,Sor",
    "Danna,Baudasso",
    "Mikael,Feaks",
    "Joli,Valentine",
    "Benedikta,Sidery",
    "Darrel,Killcross",
    "Lorie,Gingle",
    "Mignonne,Ghione",
    "Kiele,Fauguel",
    "Wilone,Woofenden",
    "Simon,Renfield",
    "Roberta,Swiffin",
    "Mirilla,Rough",
    "Dyane,Vanderplas",
    "Nedda,Stollmeyer",
    "Schuyler,Jon",
    "Gilberte,Lenahan",
    "Bevan,Caldera",
    "Sheeree,Chessum",
    "Borg,Crennan",
    "Xaviera,Donati",
    "Sula,Patey",
    "Westbrook,Geoghegan",
    "Pearl,Fritchley",
    "Eward,Frankowski",
    "Moreen,Messruther",
    "Cchaddie,Jorg",
    "Rafe,Marson",
    "Tarrah,Kadar",
    "Rhoda,McCoughan",
    "Valentine,Zarb",
    "Tomasine,Borsi",
    "Rafaelita,Storton",
    "Waldemar,Lockey",
    "Aurelia,Paine",
    "Nathaniel,Godney",
    "Vonnie,Wardhaw",
    "Alfonse,Pitney",
    "Ramonda,Bleesing",
    "Bartel,Montier",
    "Claus,Franzke",
    "Pennie,Ivanchin",
    "Mady,Iapico",
    "Bambi,Kobera",
    "Layton,Shurman",
    "Ali,Ferraraccio",
    "Onfroi,De Dantesie",
    "Hermine,Ibanez",
    "Kerby,Grigorushkin",
    "Rowland,Mabone",
    "Arabelle,Ganny",
    "Clint,Freeman",
    "Emelyne,Flaherty",
    "Nikolia,Bramhall",
    "Edythe,Roskell",
    "Moss,Lourens",
    "Casey,Venners",
    "Theodosia,Weymouth",
    "Cass,Gunson",
    "Tobey,Anselmi",
    "Hillard,Carless",
    "Cody,Piccop",
    "Amerigo,Kopecka",
    "Stuart,Knatt",
    "Giacomo,Ivanenko",
    "Penelopa,Lethebridge",
    "Franzen,Petit",
    "Genevra,Nijssen",
    "Shelli,Eliyahu",
    "Theda,Dowell",
    "Sandy,Gutridge",
    "Nickolaus,Gehrtz",
    "Tamera,Harrington",
    "Gray,Baudesson",
    "Shayne,Lamball",
    "Inglis,Wiltsher",
    "Timothy,McShirrie",
    "Harp,Huntall",
    "Maryanna,Druhan",
    "Jamey,Dissman",
    "Addi,Tidball",
    "Denver,Rings",
    "Tim,Grigoriev",
    "Saul,Alben",
    "Glyn,Kernley",
    "Abby,Pinkard",
    "Brendis,Hedlestone",
    "Leanna,Raithbie",
    "Eldin,Briggs",
    "Blondelle,Bigmore",
    "Nike,Wank",
    "Claudia,Pickover",
    "Alex,Kahen",
    "Hieronymus,Parsley",
    "Agna,Mathiassen",
    "Annecorinne,McCarron",
    "Cindie,Lebreton",
    "Zerk,Baddoe",
    "Olympia,Physick",
    "Amil,Dilland",
    "Read,Chillistone",
    "Prent,Brosetti",
    "Sissy,Cairney",
    "Tabbi,Champerlen",
    "Lynde,Benedek",
    "Vidovik,Mumm",
    "Afton,Craghead",
    "Daloris,Kopps",
    "Holden,Attock",
    "Skippy,Mabon",
    "Raymond,Lowrie",
    "Marleah,Shapiro",
    "Ragnar,Pleass",
    "Bea,Cayzer",
    "Ellary,Szimoni",
    "Bernetta,Scothorn",
    "Ezri,Docharty",
    "Thomasina,Spellacey",
    "Kaylee,Boch",
    "Shelden,Selvey",
    "Natalee,Fruish",
    "Leslie,Dreamer",
    "Johnathon,Albrook",
    "Freemon,Hardway",
    "Marietta,Gianiello",
    "Pepi,Grewe",
    "Alan,Baraja",
    "Peria,Vinker",
    "Meriel,Babb",
    "Nikos,Grafhom",
    "Eryn,Isaq",
    "Ellsworth,Hof",
    "Germain,Moors",
    "Gavra,Ruby",
    "Em,Shields",
    "Gaven,Pietasch",
    "Erna,Bugby",
    "Birk,Sumbler",
    "Dorree,Housiaux",
    "Kristos,Allbrook",
    "Fairlie,Ansett",
    "Alistair,Cauldwell",
    "Alasdair,Pena",
    "Ewan,Littell",
    "Jemima,Peret",
    "Pennie,Blanchet",
    "Cthrine,Plaister",
    "Kaja,Grayer",
    "Maressa,Philo",
    "Jeniffer,Rouzet",
    "Anita,Bumphrey",
    "Ynes,Goodacre",
    "Jaynell,Klemencic",
    "Bonita,Abeles",
    "Nalani,Tregidgo",
    "Maryjo,Mimmack",
    "Rriocard,Rawsthorne",
    "Ursulina,Galletley",
    "Milton,Ruffy",
    "Maddie,Janic",
    "Biddy,Rosenwald",
    "Alfreda,Jedrzejkiewicz",
    "Cristobal,Seth",
    "Darby,Teasey",
    "Claudetta,Loveard",
    "Zachary,Kilpatrick",
    "Ezechiel,Parfrey",
    "Gaspar,Churly",
    "Winna,Benjamin",
    "Hilarius,Benz",
    "Garth,Rao",
    "Tallulah,Tring",
    "Gawen,Hannant",
    "Jamima,Janton",
    "Frances,Dossetter",
    "Terence,Drakeford",
    "Edi,Laverenz",
    "Glen,Flores",
    "Sayre,Tremoille",
    "Dorelle,Shalders",
    "Geri,Lochhead",
    "Clayson,Knibbs",
    "Asia,Binford",
    "Garland,Walklot",
    "Mata,Lancetter",
    "Desdemona,Hudspeth",
    "Dina,Sherme",
    "Ludvig,Gahagan",
    "Riobard,Rawlinson",
    "Ruthy,Monkeman",
    "Tanner,Lexa",
    "Antoinette,Trynor",
    "Viviana,Crampsey",
    "Giffy,Erasmus",
    "Maible,Cullimore",
    "Kaile,Kenwyn",
    "Bale,Petrak",
    "Clemente,Forlonge",
    "Gloriana,Tebbet",
    "Shae,Bratten",
    "Tabatha,Frays",
    "Lanette,Ladds",
    "Dallon,Pates",
    "Gerome,Whetton",
    "Ethelred,Farfull",
    "Vida,Schops",
    "Allyce,Downing",
    "Erin,Rainville",
    "Sondra,McDugal",
    "Etta,Stopher",
    "Ferris,Ianilli",
    "Christabella,Callaby",
    "Karlotte,Francillo",
    "Uriah,Marsh",
    "Dot,Cuttle",
    "Kissee,Leppard",
    "Florian,Noe",
    "Flss,Maitland",
    "Adriena,Kilmurray",
    "Jenda,Algar",
    "Stanislaw,Tomkinson",
    "Tiffy,Baudry",
    "Sunny,Haldane",
    "Irving,Feldman",
    "Rosanne,Blair",
    "Patricia,Musgrave",
    "Joelly,Ferrao",
    "Isak,Mashro",
    "Lorrayne,Askam",
    "Gray,Muir",
    "Sammie,Stacey",
    "Raychel,Yann",
    "Jeffry,Vlies",
    "Burlie,Buckoke",
    "Porty,Bromell",
    "Cherie,Bonfield",
    "Griff,Gatsby",
    "Sinclare,Ilchuk",
    "Brianne,Rantoull",
    "Nicholas,Jacobson",
    "Pembroke,Sammut",
    "Wye,Lugg",
    "Kleon,Durrington",
    "Luciana,Boreham",
    "Devondra,Peggs",
    "Burnard,Pochon",
    "Hilary,Dat",
    "Amara,Reicherz",
    "Alric,Doy",
    "Sayre,Rimell",
    "Waiter,Shimman",
    "Ricky,Bedle",
    "Blondy,Choppen",
    "Layton,Gaven",
    "Charisse,Casaccia",
    "Batsheva,McGurgan",
    "Igor,Parramore",
    "Melita,Eydel",
    "Ashly,Maliphant",
    "Judy,Tugwell",
    "Sherye,Mulholland",
    "Seumas,Stanion",
    "Rusty,Pratley",
    "Allard,Catterell",
    "Hedy,Severn",
    "Bradan,Guinane",
    "Edith,Ouldcott",
    "Flinn,Merrgan",
    "Merissa,Quoit",
    "Timothy,Ledger",
    "Blondie,Enochsson",
    "Krystalle,Petett",
    "Yvonne,Fasler",
    "Angela,Bascombe",
    "Damita,Berrycloth",
    "Meryl,Laste",
    "Ebonee,Stockall",
    "Ryann,Grcic",
    "Hedi,Stanborough",
    "Arlee,Blakeley",
    "Elfrida,Regus",
    "Janey,Websdale",
    "Bertina,Cary",
    "Adrien,Pietz",
    "Josh,Wibrew",
    "Shamus,Pickering",
    "Delphinia,Peron",
    "Milissent,Bavidge",
    "Beryl,Kubas",
    "Glory,Ferschke",
    "Doralin,Soonhouse",
  ];

  const priorities = ["Angel,Giorgetti", "Nicholas,Jacobson", "Joli,Valentine"];
  const finalTournament = runTournamentWithPriorities(participants, priorities);

  const placings = swr.computePlacings(finalTournament);
  const [top1, top2, top3] = placings;
  expect(top1).toEqual(
    expect.objectContaining({
      data: "Joli,Valentine",
      points: 27,
    }),
  );
  expect(top2).toEqual(
    expect.objectContaining({
      data: "Nicholas,Jacobson",
      points: 24,
    }),
  );
  expect(top3).toEqual(
    expect.objectContaining({
      data: "Angel,Giorgetti",
      points: 21,
    }),
  );
});
test("should not repeat pairings throughout the tournament", () => {
  const participants = [
    "Erda,Terrington",
    "Kaleena,Laimable",
    "Kelwin,Caulcutt",
    "Noell,Stuckes",
    "Angel,Giorgetti",
    "Abbi,Mion",
    "Shanan,Cheesley",
    "Jaclyn,Coverley",
    "Dev,Padilla",
    "Crawford,Peckham",
    "Annaliese,Waiton",
    "Merci,Rallin",
    "Kincaid,Cockney",
    "Aridatha,Cronk",
    "Douglass,Jersch",
    "Hasheem,Gert",
    "Aurie,Maffini",
    "Mill,Grovier",
    "Lethia,Dudin",
    "Iormina,Pargiter",
    "Faydra,Pretti",
    "Nevin,Haddleton",
    "Peyton,Vella",
    "Marquita,Paradis",
    "Alick,Eaton",
    "Doris,Faircley",
    "Lauren,Bockmann",
    "Nissa,Liveing",
    "Titus,Jenner",
    "Elna,Ruslen",
    "Dalli,Glasson",
    "Aubree,Graffham",
    "Franklin,Veysey",
    "Jennilee,Howroyd",
    "Willie,Chittleburgh",
    "Madelina,Haseldine",
    "Darleen,O'Rourke",
    "Dion,Roubert",
    "Felipe,O'Kynsillaghe",
    "Micah,Claris",
    "Beulah,Delacoste",
    "Tarah,Slot",
    "Gay,Challes",
    "Carol-jean,Perotti",
    "Aubine,Bysaker",
    "Misha,Beteriss",
    "Pierette,Gillcrist",
    "Saundra,Droogan",
    "Calida,Hardisty",
    "Roby,Schuricht",
    "Ange,Senten",
    "Nixie,Gomery",
    "Melisenda,Elnor",
    "Marshal,Fowlie",
    "Sayre,Geffcock",
    "Rawley,Cassidy",
    "Brigham,Coad",
    "Katrina,Saipy",
    "Carey,Upshall",
    "Jeanette,Thomas",
    "Hilary,de Keep",
    "Joli,Oseman",
    "Ignatius,Macro",
    "Martie,Wilmut",
    "Janine,Dudgeon",
    "Kenon,Copozio",
    "Jecho,Winley",
    "Haydon,Dreakin",
    "Thorny,Carnock",
    "Ardelia,Itzkovitch",
    "Saree,Rolfe",
    "Brade,Romanini",
    "Zebulon,Penas",
    "Sibel,Bloss",
    "Skip,Mechi",
    "Ealasaid,Bodicum",
    "Elnora,Nye",
    "Christiane,Hamman",
    "Kenna,Huff",
    "Nathan,Lusk",
    "Hollyanne,Spottiswood",
    "Mark,Millam",
    "Henrik,Cawson",
    "Starlene,Hassur",
    "Omar,Chadney",
    "Melessa,Pentycross",
    "Tammi,Bescoby",
    "Warren,Durden",
    "Germayne,Blanking",
    "Valene,Sweett",
    "Pavel,Dell Casa",
    "Hashim,Barbosa",
    "Adolpho,Jelliman",
    "Whitman,Breacher",
    "Yardley,Habden",
    "Wilton,Hackly",
    "Lon,Bevan",
    "Brander,Lathom",
    "Jaynell,Skillings",
    "Nariko,MacAloren",
    "Sabra,Grocock",
    "Donni,Flatt",
    "Winifield,Feasby",
    "Evvy,Howard - Gater",
    "Evonne,Grenshields",
    "Addison,Child",
    "Huberto,McLeoid",
    "Ricky,Illing",
    "Berke,Bohin",
    "Pietrek,Rimer",
    "Maure,Barney",
    "Sascha,Puddin",
    "Daveen,Geist",
    "Putnem,Kemitt",
    "Adaline,Dedney",
    "Harry,Smurfitt",
    "Robena,Barton",
    "Jessey,Piner",
    "Stacee,Jasik",
    "Tally,Roan",
    "Emmet,Girton",
    "Glynis,Ricketts",
    "Jody,Obey",
    "Sergent,Southey",
    "Sandie,Mc Carrick",
    "Brody,Sawdy",
    "Lynelle,Brown",
    "Griffith,Terrington",
    "Billy,Lurriman",
    "Caroljean,Nickell",
    "Cornelle,Eccott",
    "Salli,Brayson",
    "Scottie,Farguhar",
    "Jackie,Seligson",
    "Gavin,Sadgrove",
    "Stanley,Schapero",
    "Correy,Hagstone",
    "Lacey,Hogben",
    "Amerigo,Carvil",
    "Welsh,Pestridge",
    "Ulrikaumeko,Macconaghy",
    "Penn,Housley",
    "Clim,Cutting",
    "Leshia,Sherington",
    "Alison,Quimby",
    "Emeline,Hebbron",
    "Jillian,Jenckes",
    "Lorrie,Mucklestone",
    "Malachi,Von Salzberg",
    "Hallsy,Sewley",
    "Cole,Bullerwell",
    "Missie,Elles",
    "Nerte,Hundal",
    "Hali,Cressey",
    "Devinne,Whereat",
    "Jayson,Stiggers",
    "Brinna,Shorthill",
    "Costa,Hallgalley",
    "Mendy,Korneichuk",
    "Dexter,Tollerton",
    "Jimmy,Krammer",
    "Juieta,Dosdale",
    "Trixi,Issac",
    "Bobine,Phillipps",
    "Federica,Brunnen",
    "Karrah,Hawson",
    "Verna,Spear",
    "Gracie,Tomashov",
    "Waylin,Palliser",
    "Rodina,Threadgould",
    "Lyle,Bisiker",
    "Margaretta,Haestier",
    "Cathrin,Barents",
    "Cori,Shorton",
    "Pascal,Peperell",
    "Kayle,Applegate",
    "Mord,Rosbrough",
    "Jamaal,Prince",
    "Gerrie,Birkhead",
    "Caddric,Baudain",
    "Latashia,Cartmer",
    "Harbert,Renhard",
    "Artemus,Atack",
    "Miquela,Euler",
    "Edita,Radnage",
    "Tiffie,Portigall",
    "Cornelius,Hoyland",
    "Eustace,Toombs",
    "Cointon,Bills",
    "Veda,Harget",
    "Jacquenette,Clapton",
    "Heddie,Ryburn",
    "Borden,Guesford",
    "Cammy,Oxborough",
    "Jodi,Klimkov",
    "Cecil,Ferrillo",
    "Tine,Higgen",
    "Nichols,Hatchette",
    "Bettina,Hadlee",
    "Koralle,Dennes",
    "Timmy,Edgeon",
    "Jake,Shieber",
    "Paloma,Whitford",
    "Mallorie,Cleminshaw",
    "Meredithe,Swan",
    "Micki,Skiplorne",
    "Wilfred,Imrie",
    "Shelbi,Lethbrig",
    "Vally,Yosevitz",
    "Britte,Gritland",
    "Fanechka,Brognot",
    "Gwenneth,Norval",
    "Alene,Sweeting",
    "Johanna,Dalziell",
    "Ruy,Lusted",
    "Web,Blinde",
    "Cinda,Edser",
    "Lesya,Woodfield",
    "Nikolai,Shevelin",
    "Billi,Priestland",
    "Veradis,Peggrem",
    "Penn,Sor",
    "Danna,Baudasso",
    "Mikael,Feaks",
    "Joli,Valentine",
    "Benedikta,Sidery",
    "Darrel,Killcross",
    "Lorie,Gingle",
    "Mignonne,Ghione",
    "Kiele,Fauguel",
    "Wilone,Woofenden",
    "Simon,Renfield",
    "Roberta,Swiffin",
    "Mirilla,Rough",
    "Dyane,Vanderplas",
    "Nedda,Stollmeyer",
    "Schuyler,Jon",
    "Gilberte,Lenahan",
    "Bevan,Caldera",
    "Sheeree,Chessum",
    "Borg,Crennan",
    "Xaviera,Donati",
    "Sula,Patey",
    "Westbrook,Geoghegan",
    "Pearl,Fritchley",
    "Eward,Frankowski",
    "Moreen,Messruther",
    "Cchaddie,Jorg",
    "Rafe,Marson",
    "Tarrah,Kadar",
    "Rhoda,McCoughan",
    "Valentine,Zarb",
    "Tomasine,Borsi",
    "Rafaelita,Storton",
    "Waldemar,Lockey",
    "Aurelia,Paine",
    "Nathaniel,Godney",
    "Vonnie,Wardhaw",
    "Alfonse,Pitney",
    "Ramonda,Bleesing",
    "Bartel,Montier",
    "Claus,Franzke",
    "Pennie,Ivanchin",
    "Mady,Iapico",
    "Bambi,Kobera",
    "Layton,Shurman",
    "Ali,Ferraraccio",
    "Onfroi,De Dantesie",
    "Hermine,Ibanez",
    "Kerby,Grigorushkin",
    "Rowland,Mabone",
    "Arabelle,Ganny",
    "Clint,Freeman",
    "Emelyne,Flaherty",
    "Nikolia,Bramhall",
    "Edythe,Roskell",
    "Moss,Lourens",
    "Casey,Venners",
    "Theodosia,Weymouth",
    "Cass,Gunson",
    "Tobey,Anselmi",
    "Hillard,Carless",
    "Cody,Piccop",
    "Amerigo,Kopecka",
    "Stuart,Knatt",
    "Giacomo,Ivanenko",
    "Penelopa,Lethebridge",
    "Franzen,Petit",
    "Genevra,Nijssen",
    "Shelli,Eliyahu",
    "Theda,Dowell",
    "Sandy,Gutridge",
    "Nickolaus,Gehrtz",
    "Tamera,Harrington",
    "Gray,Baudesson",
    "Shayne,Lamball",
    "Inglis,Wiltsher",
    "Timothy,McShirrie",
    "Harp,Huntall",
    "Maryanna,Druhan",
    "Jamey,Dissman",
    "Addi,Tidball",
    "Denver,Rings",
    "Tim,Grigoriev",
    "Saul,Alben",
    "Glyn,Kernley",
    "Abby,Pinkard",
    "Brendis,Hedlestone",
    "Leanna,Raithbie",
    "Eldin,Briggs",
    "Blondelle,Bigmore",
    "Nike,Wank",
    "Claudia,Pickover",
    "Alex,Kahen",
    "Hieronymus,Parsley",
    "Agna,Mathiassen",
    "Annecorinne,McCarron",
    "Cindie,Lebreton",
    "Zerk,Baddoe",
    "Olympia,Physick",
    "Amil,Dilland",
    "Read,Chillistone",
    "Prent,Brosetti",
    "Sissy,Cairney",
    "Tabbi,Champerlen",
    "Lynde,Benedek",
    "Vidovik,Mumm",
    "Afton,Craghead",
    "Daloris,Kopps",
    "Holden,Attock",
    "Skippy,Mabon",
    "Raymond,Lowrie",
    "Marleah,Shapiro",
    "Ragnar,Pleass",
    "Bea,Cayzer",
    "Ellary,Szimoni",
    "Bernetta,Scothorn",
    "Ezri,Docharty",
    "Thomasina,Spellacey",
    "Kaylee,Boch",
    "Shelden,Selvey",
    "Natalee,Fruish",
    "Leslie,Dreamer",
    "Johnathon,Albrook",
    "Freemon,Hardway",
    "Marietta,Gianiello",
    "Pepi,Grewe",
    "Alan,Baraja",
    "Peria,Vinker",
    "Meriel,Babb",
    "Nikos,Grafhom",
    "Eryn,Isaq",
    "Ellsworth,Hof",
    "Germain,Moors",
    "Gavra,Ruby",
    "Em,Shields",
    "Gaven,Pietasch",
    "Erna,Bugby",
    "Birk,Sumbler",
    "Dorree,Housiaux",
    "Kristos,Allbrook",
    "Fairlie,Ansett",
    "Alistair,Cauldwell",
    "Alasdair,Pena",
    "Ewan,Littell",
    "Jemima,Peret",
    "Pennie,Blanchet",
    "Cthrine,Plaister",
    "Kaja,Grayer",
    "Maressa,Philo",
    "Jeniffer,Rouzet",
    "Anita,Bumphrey",
    "Ynes,Goodacre",
    "Jaynell,Klemencic",
    "Bonita,Abeles",
    "Nalani,Tregidgo",
    "Maryjo,Mimmack",
    "Rriocard,Rawsthorne",
    "Ursulina,Galletley",
    "Milton,Ruffy",
    "Maddie,Janic",
    "Biddy,Rosenwald",
    "Alfreda,Jedrzejkiewicz",
    "Cristobal,Seth",
    "Darby,Teasey",
    "Claudetta,Loveard",
    "Zachary,Kilpatrick",
    "Ezechiel,Parfrey",
    "Gaspar,Churly",
    "Winna,Benjamin",
    "Hilarius,Benz",
    "Garth,Rao",
    "Tallulah,Tring",
    "Gawen,Hannant",
    "Jamima,Janton",
    "Frances,Dossetter",
    "Terence,Drakeford",
    "Edi,Laverenz",
    "Glen,Flores",
    "Sayre,Tremoille",
    "Dorelle,Shalders",
    "Geri,Lochhead",
    "Clayson,Knibbs",
    "Asia,Binford",
    "Garland,Walklot",
    "Mata,Lancetter",
    "Desdemona,Hudspeth",
    "Dina,Sherme",
    "Ludvig,Gahagan",
    "Riobard,Rawlinson",
    "Ruthy,Monkeman",
    "Tanner,Lexa",
    "Antoinette,Trynor",
    "Viviana,Crampsey",
    "Giffy,Erasmus",
    "Maible,Cullimore",
    "Kaile,Kenwyn",
    "Bale,Petrak",
    "Clemente,Forlonge",
    "Gloriana,Tebbet",
    "Shae,Bratten",
    "Tabatha,Frays",
    "Lanette,Ladds",
    "Dallon,Pates",
    "Gerome,Whetton",
    "Ethelred,Farfull",
    "Vida,Schops",
    "Allyce,Downing",
    "Erin,Rainville",
    "Sondra,McDugal",
    "Etta,Stopher",
    "Ferris,Ianilli",
    "Christabella,Callaby",
    "Karlotte,Francillo",
    "Uriah,Marsh",
    "Dot,Cuttle",
    "Kissee,Leppard",
    "Florian,Noe",
    "Flss,Maitland",
    "Adriena,Kilmurray",
    "Jenda,Algar",
    "Stanislaw,Tomkinson",
    "Tiffy,Baudry",
    "Sunny,Haldane",
    "Irving,Feldman",
    "Rosanne,Blair",
    "Patricia,Musgrave",
    "Joelly,Ferrao",
    "Isak,Mashro",
    "Lorrayne,Askam",
    "Gray,Muir",
    "Sammie,Stacey",
    "Raychel,Yann",
    "Jeffry,Vlies",
    "Burlie,Buckoke",
    "Porty,Bromell",
    "Cherie,Bonfield",
    "Griff,Gatsby",
    "Sinclare,Ilchuk",
    "Brianne,Rantoull",
    "Nicholas,Jacobson",
    "Pembroke,Sammut",
    "Wye,Lugg",
    "Kleon,Durrington",
    "Luciana,Boreham",
    "Devondra,Peggs",
    "Burnard,Pochon",
    "Hilary,Dat",
    "Amara,Reicherz",
    "Alric,Doy",
    "Sayre,Rimell",
    "Waiter,Shimman",
    "Ricky,Bedle",
    "Blondy,Choppen",
    "Layton,Gaven",
    "Charisse,Casaccia",
    "Batsheva,McGurgan",
    "Igor,Parramore",
    "Melita,Eydel",
    "Ashly,Maliphant",
    "Judy,Tugwell",
    "Sherye,Mulholland",
    "Seumas,Stanion",
    "Rusty,Pratley",
    "Allard,Catterell",
    "Hedy,Severn",
    "Bradan,Guinane",
    "Edith,Ouldcott",
    "Flinn,Merrgan",
    "Merissa,Quoit",
    "Timothy,Ledger",
    "Blondie,Enochsson",
    "Krystalle,Petett",
    "Yvonne,Fasler",
    "Angela,Bascombe",
    "Damita,Berrycloth",
    "Meryl,Laste",
    "Ebonee,Stockall",
    "Ryann,Grcic",
    "Hedi,Stanborough",
    "Arlee,Blakeley",
    "Elfrida,Regus",
    "Janey,Websdale",
    "Bertina,Cary",
    "Adrien,Pietz",
    "Josh,Wibrew",
    "Shamus,Pickering",
    "Delphinia,Peron",
    "Milissent,Bavidge",
    "Beryl,Kubas",
    "Glory,Ferschke",
    "Doralin,Soonhouse",
  ];

  const priorities = ["Angel,Giorgetti", "Nicholas,Jacobson", "Joli,Valentine"];
  const { rounds } = runTournamentWithPriorities(participants, priorities);

  fs.writeFileSync("test-rounds.json", JSON.stringify(rounds, null, 4));

  const uniquePairings = new Set();
  rounds.forEach((matches, i) => {
    matches.forEach((match, j) => {
      const id = createUniquePairingIdentifier(match);
      uniquePairings.add(id);
    });
  });

  expect(uniquePairings.size).toEqual(256 * 9);
});

test("should not repeat pairings throughout the tournament even with byes", () => {
  const participants = [
    "Erda,Terrington",
    "Kaleena,Laimable",
    "Kelwin,Caulcutt",
    "Noell,Stuckes",
    "Angel,Giorgetti",
    "Abbi,Mion",
    "Shanan,Cheesley",
    "Jaclyn,Coverley",
    "Dev,Padilla",
    "Crawford,Peckham",
    "Annaliese,Waiton",
    "Merci,Rallin",
    "Kincaid,Cockney",
    "Aridatha,Cronk",
    "Douglass,Jersch",
    "Hasheem,Gert",
    "Aurie,Maffini",
    "Mill,Grovier",
    "Lethia,Dudin",
    "Iormina,Pargiter",
    "Faydra,Pretti",
    "Nevin,Haddleton",
    "Peyton,Vella",
    "Marquita,Paradis",
    "Alick,Eaton",
    "Doris,Faircley",
    "Lauren,Bockmann",
    "Nissa,Liveing",
    "Titus,Jenner",
    "Elna,Ruslen",
    "Dalli,Glasson",
    "Aubree,Graffham",
    "Franklin,Veysey",
    "Jennilee,Howroyd",
    "Willie,Chittleburgh",
    "Madelina,Haseldine",
    "Darleen,O'Rourke",
    "Dion,Roubert",
    "Felipe,O'Kynsillaghe",
    "Micah,Claris",
    "Beulah,Delacoste",
    "Tarah,Slot",
    "Gay,Challes",
    "Carol-jean,Perotti",
    "Aubine,Bysaker",
    "Misha,Beteriss",
    "Pierette,Gillcrist",
    "Saundra,Droogan",
    "Calida,Hardisty",
    "Roby,Schuricht",
    "Ange,Senten",
    "Nixie,Gomery",
    "Melisenda,Elnor",
    "Marshal,Fowlie",
    "Sayre,Geffcock",
    "Rawley,Cassidy",
    "Brigham,Coad",
    "Katrina,Saipy",
    "Carey,Upshall",
    "Jeanette,Thomas",
    "Hilary,de Keep",
    "Joli,Oseman",
    "Ignatius,Macro",
    "Martie,Wilmut",
    "Janine,Dudgeon",
    "Kenon,Copozio",
    "Jecho,Winley",
    "Haydon,Dreakin",
    "Thorny,Carnock",
    "Ardelia,Itzkovitch",
    "Saree,Rolfe",
    "Brade,Romanini",
    "Zebulon,Penas",
    "Sibel,Bloss",
    "Skip,Mechi",
    "Ealasaid,Bodicum",
    "Elnora,Nye",
    "Christiane,Hamman",
    "Kenna,Huff",
    "Nathan,Lusk",
    "Hollyanne,Spottiswood",
    "Mark,Millam",
    "Henrik,Cawson",
    "Starlene,Hassur",
    "Omar,Chadney",
    "Melessa,Pentycross",
    "Tammi,Bescoby",
    "Warren,Durden",
    "Germayne,Blanking",
    "Valene,Sweett",
    "Pavel,Dell Casa",
    "Hashim,Barbosa",
    "Adolpho,Jelliman",
    "Whitman,Breacher",
    "Yardley,Habden",
    "Wilton,Hackly",
    "Lon,Bevan",
    "Brander,Lathom",
    "Jaynell,Skillings",
    "Nariko,MacAloren",
    "Sabra,Grocock",
    "Donni,Flatt",
    "Winifield,Feasby",
    "Evvy,Howard - Gater",
    "Evonne,Grenshields",
    "Addison,Child",
    "Huberto,McLeoid",
    "Ricky,Illing",
    "Berke,Bohin",
    "Pietrek,Rimer",
    "Maure,Barney",
    "Sascha,Puddin",
    "Daveen,Geist",
    "Putnem,Kemitt",
    "Adaline,Dedney",
    "Harry,Smurfitt",
    "Robena,Barton",
    "Jessey,Piner",
    "Stacee,Jasik",
    "Tally,Roan",
    "Emmet,Girton",
    "Glynis,Ricketts",
    "Jody,Obey",
    "Sergent,Southey",
    "Sandie,Mc Carrick",
    "Brody,Sawdy",
    "Lynelle,Brown",
    "Griffith,Terrington",
    "Billy,Lurriman",
    "Caroljean,Nickell",
    "Cornelle,Eccott",
    "Salli,Brayson",
    "Scottie,Farguhar",
    "Jackie,Seligson",
    "Gavin,Sadgrove",
    "Stanley,Schapero",
    "Correy,Hagstone",
    "Lacey,Hogben",
    "Amerigo,Carvil",
    "Welsh,Pestridge",
    "Ulrikaumeko,Macconaghy",
    "Penn,Housley",
    "Clim,Cutting",
    "Leshia,Sherington",
    "Alison,Quimby",
    "Emeline,Hebbron",
    "Jillian,Jenckes",
    "Lorrie,Mucklestone",
    "Malachi,Von Salzberg",
    "Hallsy,Sewley",
    "Cole,Bullerwell",
    "Missie,Elles",
    "Nerte,Hundal",
    "Hali,Cressey",
    "Devinne,Whereat",
    "Jayson,Stiggers",
    "Brinna,Shorthill",
    "Costa,Hallgalley",
    "Mendy,Korneichuk",
    "Dexter,Tollerton",
    "Jimmy,Krammer",
    "Juieta,Dosdale",
    "Trixi,Issac",
    "Bobine,Phillipps",
    "Federica,Brunnen",
    "Karrah,Hawson",
    "Verna,Spear",
    "Gracie,Tomashov",
    "Waylin,Palliser",
    "Rodina,Threadgould",
    "Lyle,Bisiker",
    "Margaretta,Haestier",
    "Cathrin,Barents",
    "Cori,Shorton",
    "Pascal,Peperell",
    "Kayle,Applegate",
    "Mord,Rosbrough",
    "Jamaal,Prince",
    "Gerrie,Birkhead",
    "Caddric,Baudain",
    "Latashia,Cartmer",
    "Harbert,Renhard",
    "Artemus,Atack",
    "Miquela,Euler",
    "Edita,Radnage",
    "Tiffie,Portigall",
    "Cornelius,Hoyland",
    "Eustace,Toombs",
    "Cointon,Bills",
    "Veda,Harget",
    "Jacquenette,Clapton",
    "Heddie,Ryburn",
    "Borden,Guesford",
    "Cammy,Oxborough",
    "Jodi,Klimkov",
    "Cecil,Ferrillo",
    "Tine,Higgen",
    "Nichols,Hatchette",
    "Bettina,Hadlee",
    "Koralle,Dennes",
    "Timmy,Edgeon",
    "Jake,Shieber",
    "Paloma,Whitford",
    "Mallorie,Cleminshaw",
    "Meredithe,Swan",
    "Micki,Skiplorne",
    "Wilfred,Imrie",
    "Shelbi,Lethbrig",
    "Vally,Yosevitz",
    "Britte,Gritland",
    "Fanechka,Brognot",
    "Gwenneth,Norval",
    "Alene,Sweeting",
    "Johanna,Dalziell",
    "Ruy,Lusted",
    "Web,Blinde",
    "Cinda,Edser",
    "Lesya,Woodfield",
    "Nikolai,Shevelin",
    "Billi,Priestland",
    "Veradis,Peggrem",
    "Penn,Sor",
    "Danna,Baudasso",
    "Mikael,Feaks",
    "Joli,Valentine",
    "Benedikta,Sidery",
    "Darrel,Killcross",
    "Lorie,Gingle",
    "Mignonne,Ghione",
    "Kiele,Fauguel",
    "Wilone,Woofenden",
    "Simon,Renfield",
    "Roberta,Swiffin",
    "Mirilla,Rough",
    "Dyane,Vanderplas",
    "Nedda,Stollmeyer",
    "Schuyler,Jon",
    "Gilberte,Lenahan",
    "Bevan,Caldera",
    "Sheeree,Chessum",
    "Borg,Crennan",
    "Xaviera,Donati",
    "Sula,Patey",
    "Westbrook,Geoghegan",
    "Pearl,Fritchley",
    "Eward,Frankowski",
    "Moreen,Messruther",
    "Cchaddie,Jorg",
    "Rafe,Marson",
    "Tarrah,Kadar",
    "Rhoda,McCoughan",
    "Valentine,Zarb",
    "Tomasine,Borsi",
    "Rafaelita,Storton",
    "Waldemar,Lockey",
    "Aurelia,Paine",
    "Nathaniel,Godney",
    "Vonnie,Wardhaw",
    "Alfonse,Pitney",
    "Ramonda,Bleesing",
    "Bartel,Montier",
    "Claus,Franzke",
    "Pennie,Ivanchin",
    "Mady,Iapico",
    "Bambi,Kobera",
    "Layton,Shurman",
    "Ali,Ferraraccio",
    "Onfroi,De Dantesie",
    "Hermine,Ibanez",
    "Kerby,Grigorushkin",
    "Rowland,Mabone",
    "Arabelle,Ganny",
    "Clint,Freeman",
    "Emelyne,Flaherty",
    "Nikolia,Bramhall",
    "Edythe,Roskell",
    "Moss,Lourens",
    "Casey,Venners",
    "Theodosia,Weymouth",
    "Cass,Gunson",
    "Tobey,Anselmi",
    "Hillard,Carless",
    "Cody,Piccop",
    "Amerigo,Kopecka",
    "Stuart,Knatt",
    "Giacomo,Ivanenko",
    "Penelopa,Lethebridge",
    "Franzen,Petit",
    "Genevra,Nijssen",
    "Shelli,Eliyahu",
    "Theda,Dowell",
    "Sandy,Gutridge",
    "Nickolaus,Gehrtz",
    "Tamera,Harrington",
    "Gray,Baudesson",
    "Shayne,Lamball",
    "Inglis,Wiltsher",
    "Timothy,McShirrie",
    "Harp,Huntall",
    "Maryanna,Druhan",
    "Jamey,Dissman",
    "Addi,Tidball",
    "Denver,Rings",
    "Tim,Grigoriev",
    "Saul,Alben",
    "Glyn,Kernley",
    "Abby,Pinkard",
    "Brendis,Hedlestone",
    "Leanna,Raithbie",
    "Eldin,Briggs",
    "Blondelle,Bigmore",
    "Nike,Wank",
    "Claudia,Pickover",
    "Alex,Kahen",
    "Hieronymus,Parsley",
    "Agna,Mathiassen",
    "Annecorinne,McCarron",
    "Cindie,Lebreton",
    "Zerk,Baddoe",
    "Olympia,Physick",
    "Amil,Dilland",
    "Read,Chillistone",
    "Prent,Brosetti",
    "Sissy,Cairney",
    "Tabbi,Champerlen",
    "Lynde,Benedek",
    "Vidovik,Mumm",
    "Afton,Craghead",
    "Daloris,Kopps",
    "Holden,Attock",
    "Skippy,Mabon",
    "Raymond,Lowrie",
    "Marleah,Shapiro",
    "Ragnar,Pleass",
    "Bea,Cayzer",
    "Ellary,Szimoni",
    "Bernetta,Scothorn",
    "Ezri,Docharty",
    "Thomasina,Spellacey",
    "Kaylee,Boch",
    "Shelden,Selvey",
    "Natalee,Fruish",
    "Leslie,Dreamer",
    "Johnathon,Albrook",
    "Freemon,Hardway",
    "Marietta,Gianiello",
    "Pepi,Grewe",
    "Alan,Baraja",
    "Peria,Vinker",
    "Meriel,Babb",
    "Nikos,Grafhom",
    "Eryn,Isaq",
    "Ellsworth,Hof",
    "Germain,Moors",
    "Gavra,Ruby",
    "Em,Shields",
    "Gaven,Pietasch",
    "Erna,Bugby",
    "Birk,Sumbler",
    "Dorree,Housiaux",
    "Kristos,Allbrook",
    "Fairlie,Ansett",
    "Alistair,Cauldwell",
    "Alasdair,Pena",
    "Ewan,Littell",
    "Jemima,Peret",
    "Pennie,Blanchet",
    "Cthrine,Plaister",
    "Kaja,Grayer",
    "Maressa,Philo",
    "Jeniffer,Rouzet",
    "Anita,Bumphrey",
    "Ynes,Goodacre",
    "Jaynell,Klemencic",
    "Bonita,Abeles",
    "Nalani,Tregidgo",
    "Maryjo,Mimmack",
    "Rriocard,Rawsthorne",
    "Ursulina,Galletley",
    "Milton,Ruffy",
    "Maddie,Janic",
    "Biddy,Rosenwald",
    "Alfreda,Jedrzejkiewicz",
    "Cristobal,Seth",
    "Darby,Teasey",
    "Claudetta,Loveard",
    "Zachary,Kilpatrick",
    "Ezechiel,Parfrey",
    "Gaspar,Churly",
    "Winna,Benjamin",
    "Hilarius,Benz",
    "Garth,Rao",
    "Tallulah,Tring",
    "Gawen,Hannant",
    "Jamima,Janton",
    "Frances,Dossetter",
    "Terence,Drakeford",
    "Edi,Laverenz",
    "Glen,Flores",
    "Sayre,Tremoille",
    "Dorelle,Shalders",
    "Geri,Lochhead",
    "Clayson,Knibbs",
    "Asia,Binford",
    "Garland,Walklot",
    "Mata,Lancetter",
    "Desdemona,Hudspeth",
    "Dina,Sherme",
    "Ludvig,Gahagan",
    "Riobard,Rawlinson",
    "Ruthy,Monkeman",
    "Tanner,Lexa",
    "Antoinette,Trynor",
    "Viviana,Crampsey",
    "Giffy,Erasmus",
    "Maible,Cullimore",
    "Kaile,Kenwyn",
    "Bale,Petrak",
    "Clemente,Forlonge",
    "Gloriana,Tebbet",
    "Shae,Bratten",
    "Tabatha,Frays",
    "Lanette,Ladds",
    "Dallon,Pates",
    "Gerome,Whetton",
    "Ethelred,Farfull",
    "Vida,Schops",
    "Allyce,Downing",
    "Erin,Rainville",
    "Sondra,McDugal",
    "Etta,Stopher",
    "Ferris,Ianilli",
    "Christabella,Callaby",
    "Karlotte,Francillo",
    "Uriah,Marsh",
    "Dot,Cuttle",
    "Kissee,Leppard",
    "Florian,Noe",
    "Flss,Maitland",
    "Adriena,Kilmurray",
    "Jenda,Algar",
    "Stanislaw,Tomkinson",
    "Tiffy,Baudry",
    "Sunny,Haldane",
    "Irving,Feldman",
    "Rosanne,Blair",
    "Patricia,Musgrave",
    "Joelly,Ferrao",
    "Isak,Mashro",
    "Lorrayne,Askam",
    "Gray,Muir",
    "Sammie,Stacey",
    "Raychel,Yann",
    "Jeffry,Vlies",
    "Burlie,Buckoke",
    "Porty,Bromell",
    "Cherie,Bonfield",
    "Griff,Gatsby",
    "Sinclare,Ilchuk",
    "Brianne,Rantoull",
    "Nicholas,Jacobson",
    "Pembroke,Sammut",
    "Wye,Lugg",
    "Kleon,Durrington",
    "Luciana,Boreham",
    "Devondra,Peggs",
    "Burnard,Pochon",
    "Hilary,Dat",
    "Amara,Reicherz",
    "Alric,Doy",
    "Sayre,Rimell",
    "Waiter,Shimman",
    "Ricky,Bedle",
    "Blondy,Choppen",
    "Layton,Gaven",
    "Charisse,Casaccia",
    "Batsheva,McGurgan",
    "Igor,Parramore",
    "Melita,Eydel",
    "Ashly,Maliphant",
    "Judy,Tugwell",
    "Sherye,Mulholland",
    "Seumas,Stanion",
    "Rusty,Pratley",
    "Allard,Catterell",
    "Hedy,Severn",
    "Bradan,Guinane",
    "Edith,Ouldcott",
    "Flinn,Merrgan",
    "Merissa,Quoit",
    "Timothy,Ledger",
    "Blondie,Enochsson",
    "Krystalle,Petett",
    "Yvonne,Fasler",
    "Angela,Bascombe",
    "Damita,Berrycloth",
    "Meryl,Laste",
    "Ebonee,Stockall",
    "Ryann,Grcic",
    "Hedi,Stanborough",
    "Arlee,Blakeley",
    "Elfrida,Regus",
    "Janey,Websdale",
    "Bertina,Cary",
    "Adrien,Pietz",
    "Josh,Wibrew",
    "Shamus,Pickering",
    "Delphinia,Peron",
    "Milissent,Bavidge",
    "Beryl,Kubas",
    "Glory,Ferschke",
  ];

  const priorities = ["Angel,Giorgetti", "Nicholas,Jacobson", "Joli,Valentine"];
  const { rounds } = runTournamentWithPriorities(participants, priorities);

  fs.writeFileSync("test-rounds.json", JSON.stringify(rounds, null, 4));

  const uniquePairings = new Set();
  rounds.forEach((matches, i) => {
    matches.forEach((match, j) => {
      const id = createUniquePairingIdentifier(match);
      uniquePairings.add(id);
    });
  });

  expect(uniquePairings.size).toEqual(256 * 9);
});

const createUniquePairingIdentifier = (match) => {
  if (match.p1 < match.p2) {
    return "" + match.p1 + "-" + match.p2;
  } else {
    return "" + match.p2 + "-" + match.p1;
  }
};
